import os
from pathlib import Path
from typing import Dict, Union

from snakemake.utils import min_version

# require minimum snakemake version
min_version("6.10.0")


# =====================================
# Constants for workflow
PathLike = Union[str, Path, os.PathLike]
GB = 1_024
# =====================================


# =====================================
# Workflow config items
configfile: "config/config.yaml"


containers: Dict[str, PathLike] = config["containers"]
# =====================================
