ont_samplesheet:      "docs/ont_samples.csv"
illumina_samplesheet: "docs/illumina_samples.csv"
nfs_data_dir:         "/nfs/research/zi/zi/projects/tb/mada-mumbai-sputum/"
basecall_config:      "dna_r9.4.1_450bps_sup_prom.cfg"
max_covg: # subsample reads to this (if over)
  illumina: 100
  nanopore: 150
genome_size:          4411532
containers:
  guppy-gpu: "docker://quay.io/mbhall88/guppy-gpu:5.0.16"
  guppy-cpu: "docker://quay.io/mbhall88/guppy-cpu:5.0.16"
  base:      "docker://bash:5.1"
  seqkit:    "docker://quay.io/biocontainers/seqkit:2.1.0--h9ee0642_0"
  rasusa:    "docker://quay.io/mbhall88/rasusa:0.6.0"
  mykrobe:   "docker://quay.io/biocontainers/mykrobe:0.10.0--py38h8e3bb3f_0"
  fastp:     "docker://quay.io/biocontainers/fastp:0.23.2--h79da9fb_0"
  nanoq:     "docker://quay.io/biocontainers/nanoq:0.8.6--hec16e2b_1"